server:
  port: 3930

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://175.193.22.60:3307/config?characterEncoding=UTF-8
    username: root
    password: dbfltjdwls

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.etl.sfdc.user.model.dto
  configuration:
    mapUnderscoreToCamelCase: true
