spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.etl.sfdc.user.model.dto
  configuration:
    mapUnderscoreToCamelCase: true

salesforce:
  clientId: ${SALESFORCE_CLIENT_ID}
  clientSecret: ${SALESFORCE_CLIENT_SECRET}
  redirectUri: ${SALESFORCE_REDIRECT_URI}
  authUrl: ${SALESFORCE_AUTH_URL}
  tokenUrl: ${SALESFORCE_TOKEN_URL}
  myDomain: ${SALESFORCE_MY_DOMAIN}